autoscalling group added

diff --git a/kubernetes-formation.yaml b/kubernetes-formation.yaml
--- a/kubernetes-formation.yaml
+++ b/kubernetes-formation.yaml
@@ -40,6 +40,8 @@ Resources:
         - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
         - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
         - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
+        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
+        - arn:aws:iam::aws:policy/service-role/AWSShieldDRTAccessPolicy
       RoleName: EC2S3FullAccessRole
 
   EC2InstanceProfile:
@@ -122,14 +124,22 @@ Resources:
           Ebs:
             VolumeSize: 20
       KeyName: !Ref KeyName
-      UserData: !Base64
-        Fn::Sub: |
+      SourceDestCheck: false
+      SubnetId: subnet-0fcfb70a5bbee3b4a
+      UserData: 
+        Fn::Base64: !Sub |
           #!/bin/bash
           # # Log all output to a file
           # sudo cat /var/log/user-data.log
           # # sudo cat /var/log/user-data.log
           # exec > /var/log/user-data.log 2>&1
           set -x  # Enable script debugging (print each command before executing)
+
+          #install aws cli
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          sudo apt install unzip
+          unzip awscliv2.zip
+          sudo ./aws/install
 
           # Disable swap
           swapoff -a
@@ -206,18 +216,27 @@ Resources:
 
           sudo mkdir -p /home/ubuntu/.kube 
           sudo cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config 
-          sudo chown root:root /home/ubuntu/.kube/config
+          sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config
 
           # Install Calico CNI
           kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
           curl https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml -O
           kubectl apply -f custom-resources.yaml
 
+          #install helm
+          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+          chmod 700 get_helm.sh
+          ./get_helm.sh
+
           #install aws csi driver
           kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.38"
 
           echo "Initializing Kubernetes namespace..."
           sudo apt install kubectx
+
+          # Set the default namespace
+          kubectl create namespace my-namespace
+          kubens my-namespace
 
           echo "Disabling AppArmor..."
           sudo systemctl stop apparmor && sudo systemctl disable apparmor
@@ -226,6 +245,16 @@ Resources:
           echo "alias k='kubectl'" >> /home/ubuntu/.bashrc
           echo "export EDITOR=nano" >> /home/ubuntu/.bashrc
 
+          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+          chmod 700 get_helm.sh
+          ./get_helm.sh
+
+          # Add the EKS chart repo
+          helm repo add eks https://aws.github.io/eks-charts
+
+          # Update the repo
+          helm repo update
+
           # Reload .bashrc
           source /home/ubuntu/.bashrc
 
@@ -233,182 +262,171 @@ Resources:
           sudo rm /etc/resolv.conf
           sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
 
-
-  EC2InstanceWorker:
-    Type: AWS::EC2::Instance
+  EC2LaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
     Properties:
-      InstanceType: t3.medium
-      ImageId: !Ref AmiIdParam
-      Tags:
-        - Key: Name
-          Value: worker-node
-      SecurityGroupIds:
-        - !Ref KubernetesSecurityGroup
-      IamInstanceProfile: !Ref EC2InstanceProfile
-      BlockDeviceMappings:
-        - DeviceName: /dev/sda1
-          Ebs:
-            VolumeSize: 20
-            VolumeType: gp3
-      KeyName: !Ref KeyName
-      UserData: !Base64
-        Fn::Sub: |
-          #!/bin/bash
-          # # Log all output to a file
-          # sudo cat /var/log/user-data.log
-          # # sudo cat /var/log/user-data.log
-          # exec > /var/log/user-data.log 2>&1
-          set -x  # Enable script debugging (print each command before executing)
+      LaunchTemplateName: worker-node-launch-template
+      VersionDescription: !Sub ${AWS::StackName}-${AWS::Region}
+      LaunchTemplateData:
+        InstanceType: t3.medium
+        ImageId: !Ref AmiIdParam
+        BlockDeviceMappings:
+          - DeviceName: /dev/sda1
+            Ebs:
+              VolumeSize: 20
+              VolumeType: gp3
+        TagSpecifications:
+          - ResourceType: instance
+            Tags:
+              - Key: Name
+                Value: worker-node
+        MetadataOptions:
+          HttpTokens: optional
+          HttpPutResponseHopLimit: 3
+        SecurityGroupIds:
+          - !Ref KubernetesSecurityGroup
+        IamInstanceProfile: 
+          Arn: !GetAtt EC2InstanceProfile.Arn
+        KeyName: !Ref KeyName
+        UserData: 
+          Fn::Base64: !Sub |
+            #!/bin/bash
+            # # Log all output to a file
+            # sudo cat /var/log/user-data.log
+            # # sudo cat /var/log/user-data.log
+            # exec > /var/log/user-data.log 2>&1
+            set -x  # Enable script debugging (print each command before executing)
 
-          # Disable swap
-          swapoff -a
-          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
+            # Disable swap
+            swapoff -a
+            sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
 
-          # Load required kernel modules
-          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
-          overlay
-          br_netfilter
-          EOF
+            #install aws cli
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            sudo apt install unzip
+            unzip awscliv2.zip
+            sudo ./aws/install
 
-          sudo modprobe overlay
-          sudo modprobe br_netfilter
+            # Load required kernel modules
+            cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
+            overlay
+            br_netfilter
+            EOF
 
-          # Set sysctl parameters for Kubernetes networking
-          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
-          net.bridge.bridge-nf-call-iptables  = 1
-          net.bridge.bridge-nf-call-ip6tables = 1
-          net.ipv4.ip_forward                 = 1
-          EOF
+            sudo modprobe overlay
+            sudo modprobe br_netfilter
 
-          sudo sysctl --system
+            # Set sysctl parameters for Kubernetes networking
+            cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
+            net.bridge.bridge-nf-call-iptables  = 1
+            net.bridge.bridge-nf-call-ip6tables = 1
+            net.ipv4.ip_forward                 = 1
+            EOF
 
-          # Verify kernel modules and sysctl parameters
-          lsmod | grep br_netfilter || echo "br_netfilter module not loaded"
-          lsmod | grep overlay || echo "overlay module not loaded"
-          sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward || echo "Sysctl parameters not set correctly"
+            sudo sysctl --system
 
-          # Install containerd
-          curl -LO https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz
-          sudo tar Cxzvf /usr/local containerd-1.7.14-linux-amd64.tar.gz
-          curl -LO https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
-          sudo mkdir -p /usr/local/lib/systemd/system/
-          sudo mv containerd.service /usr/local/lib/systemd/system/
-          sudo mkdir -p /etc/containerd
-          containerd config default | sudo tee /etc/containerd/config.toml
-          sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
-          sudo systemctl daemon-reload
-          sudo systemctl enable --now containerd
+            # Verify kernel modules and sysctl parameters
+            lsmod | grep br_netfilter || echo "br_netfilter module not loaded"
+            lsmod | grep overlay || echo "overlay module not loaded"
+            sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward || echo "Sysctl parameters not set correctly"
 
-          # Verify containerd service is running
-          if ! systemctl status containerd; then
-            echo "Containerd service failed to start!"
-          fi
+            # Install containerd
+            curl -LO https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz
+            sudo tar Cxzvf /usr/local containerd-1.7.14-linux-amd64.tar.gz
+            curl -LO https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
+            sudo mkdir -p /usr/local/lib/systemd/system/
+            sudo mv containerd.service /usr/local/lib/systemd/system/
+            sudo mkdir -p /etc/containerd
+            containerd config default | sudo tee /etc/containerd/config.toml
+            sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
+            sudo systemctl daemon-reload
+            sudo systemctl enable --now containerd
 
-          # Install runc
-          curl -LO https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
-          sudo install -m 755 runc.amd64 /usr/local/sbin/runc
+            # Verify containerd service is running
+            if ! systemctl status containerd; then
+              echo "Containerd service failed to start!"
+            fi
 
-          # Add Kubernetes package repository and install kubelet, kubeadm, kubectl
-          sudo apt-get update
-          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
-          sudo mkdir -p /etc/apt/keyrings
-          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
-          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
-          sudo apt-get update
-          sudo apt-get install -y kubelet=1.29.6-1.1 kubeadm=1.29.6-1.1 kubectl=1.29.6-1.1 --allow-downgrades --allow-change-held-packages
-          sudo apt-mark hold kubelet kubeadm kubectl
-          
-          echo "Initializing Kubernetes cluster..."
-          sudo apt install kubectx
+            # Install runc
+            curl -LO https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
+            sudo install -m 755 runc.amd64 /usr/local/sbin/runc
 
-          echo "Disabling AppArmor..."
-          sudo systemctl stop apparmor && sudo systemctl disable apparmor
+            # Add Kubernetes package repository and install kubelet, kubeadm, kubectl
+            sudo apt-get update
+            sudo apt-get install -y apt-transport-https ca-certificates curl gpg
+            sudo mkdir -p /etc/apt/keyrings
+            curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+            echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
+            sudo apt-get update
+            sudo apt-get install -y kubelet=1.29.6-1.1 kubeadm=1.29.6-1.1 kubectl=1.29.6-1.1 --allow-downgrades --allow-change-held-packages
+            sudo apt-mark hold kubelet kubeadm kubectl
+            
+            echo "Initializing Kubernetes cluster..."
+            sudo apt install kubectx
 
-  EC2InstanceWorker2:
-    Type: AWS::EC2::Instance
+            echo "Disabling AppArmor..."
+            sudo systemctl stop apparmor && sudo systemctl disable apparmor
+
+            KEY_CONTENT=$(aws ssm get-parameter \
+            --name "ssh-private-keys-mykey" \
+            --with-decryption \
+            --region ${AWS::Region} \
+            --query 'Parameter.Value' \
+            --output text)
+            KEY_FILE="/tmp/private_key"
+            echo "$KEY_CONTENT" > "$KEY_FILE"
+            chmod 600 "$KEY_FILE"
+
+            MASTER_IP=${EC2Instance.PrivateIp}
+            JOIN_COMMAND=$(ssh -o StrictHostKeyChecking=no -i "$KEY_FILE" ubuntu@$MASTER_IP 'sudo kubeadm token create --print-join-command')
+            eval "sudo $JOIN_COMMAND"
+
+            sudo mkdir -p /root/.kube 
+            sudo cp /etc/kubernetes/kubelet.conf /root/.kube/config
+            rm -f "$KEY_FILE"
+
+            # Get instance metadata
+            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
+            INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+            REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
+
+            # set the PROVIDER_ID
+            PROVIDER_ID="aws:///$(REGION)/$(INSTANCE_ID)"
+
+            # Then use the patch command
+            sudo kubectl patch node $(hostname) -p "{\"spec\":{\"providerID\":\"$(PROVIDER_ID)\"}}"
+            sudo kubectl label nodes $(hostname) env=production
+
+            # Restart the kubelet service
+            sudo systemctl daemon-reload
+            sudo systemctl restart kubelet
+
+  AutoScalingGroup:
+    Type: AWS::AutoScaling::AutoScalingGroup
     Properties:
-      InstanceType: t3.medium
-      ImageId: !Ref AmiIdParam
-      Tags:
-        - Key: Name
-          Value: worker-node
-      SecurityGroupIds:
-        - !Ref KubernetesSecurityGroup
-      IamInstanceProfile: !Ref EC2InstanceProfile
-      BlockDeviceMappings:
-        - DeviceName: /dev/sda1
-          Ebs:
-            VolumeSize: 20
-      KeyName: !Ref KeyName
-      UserData: !Base64
-        Fn::Sub: |
-          #!/bin/bash
-          # # Log all output to a file
-          # sudo cat /var/log/user-data.log
-          # # sudo cat /var/log/user-data.log
-          # exec > /var/log/user-data.log 2>&1
-          set -x  # Enable script debugging (print each command before executing)
-
-          # Disable swap
-          swapoff -a
-          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
-
-          # Load required kernel modules
-          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
-          overlay
-          br_netfilter
-          EOF
-
-          sudo modprobe overlay
-          sudo modprobe br_netfilter
-
-          # Set sysctl parameters for Kubernetes networking
-          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
-          net.bridge.bridge-nf-call-iptables  = 1
-          net.bridge.bridge-nf-call-ip6tables = 1
-          net.ipv4.ip_forward                 = 1
-          EOF
-
-          sudo sysctl --system
-
-          # Verify kernel modules and sysctl parameters
-          lsmod | grep br_netfilter || echo "br_netfilter module not loaded"
-          lsmod | grep overlay || echo "overlay module not loaded"
-          sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward || echo "Sysctl parameters not set correctly"
-
-          # Install containerd
-          curl -LO https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz
-          sudo tar Cxzvf /usr/local containerd-1.7.14-linux-amd64.tar.gz
-          curl -LO https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
-          sudo mkdir -p /usr/local/lib/systemd/system/
-          sudo mv containerd.service /usr/local/lib/systemd/system/
-          sudo mkdir -p /etc/containerd
-          containerd config default | sudo tee /etc/containerd/config.toml
-          sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
-          sudo systemctl daemon-reload
-          sudo systemctl enable --now containerd
-
-          # Verify containerd service is running
-          if ! systemctl status containerd; then
-            echo "Containerd service failed to start!"
-          fi
-
-          # Install runc
-          curl -LO https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
-          sudo install -m 755 runc.amd64 /usr/local/sbin/runc
-
-          # Add Kubernetes package repository and install kubelet, kubeadm, kubectl
-          sudo apt-get update
-          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
-          sudo mkdir -p /etc/apt/keyrings
-          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
-          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
-          sudo apt-get update
-          sudo apt-get install -y kubelet=1.29.6-1.1 kubeadm=1.29.6-1.1 kubectl=1.29.6-1.1 --allow-downgrades --allow-change-held-packages
-          sudo apt-mark hold kubelet kubeadm kubectl
-          
-          echo "Initializing Kubernetes cluster..."
-          sudo apt install kubectx
-
-          echo "Disabling AppArmor..."
-          sudo systemctl stop apparmor && sudo systemctl disable apparmor
+      AutoScalingGroupName: !Sub ${AWS::StackName}-asg
+      MinSize: 1
+      MaxSize: 5
+      DesiredCapacity: 2
+      HealthCheckType: EC2
+      LaunchTemplate:
+        LaunchTemplateId: !Ref EC2LaunchTemplate
+        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
+      VPCZoneIdentifier:
+        - subnet-0fcfb70a5bbee3b4a
+      Tags: 
+        - Key: k8s.io/cluster-autoscaler/enabled
+          PropagateAtLaunch: true
+          Value: true
+        - Key: k8s.io/cluster-autoscaler/kubernetes
+          PropagateAtLaunch: true
+          Value: owned
+      
+  # EC2InstanceWorker:
+  #   Type: AWS::EC2::Instance
+  #   Properties:
+  #     LaunchTemplate:
+  #       LaunchTemplateId: !Ref EC2LaunchTemplate
+  #       Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
+  #     SubnetId: subnet-0fcfb70a5bbee3b4a
+  #     SourceDestCheck: false
